"""Interpretation under constraint.

Two business rules govern everything in this package, and they are the reason
it exists as a separate layer rather than as a prompt:

* **BR-13** — no text freely generated by a language model is displayed as an
  analytical conclusion.
* **BR-14** — no interpretation calls a ratio favourable or unfavourable
  without an explicit reference: a prior period, or a documented threshold.

So an interpretation here is a *template plus the thresholds actually
applied*. The sentence shown to a client can always be traced back to the
rule that produced it. A model that writes "liquidity is comfortable" cannot
be audited; a template that writes "1.4 x, above the 1.0 threshold stated in
the methodological note" can.

Dossier §12.1 (Interpretation), §3.2 (interpretation in scope), §20.1 (the
business relevance of the interpretation is explicitly *not* evaluated —
only its conformity to its template and declared thresholds).
"""

from .templates import (
    NO_REFERENCE,
    Interpretation,
    Threshold,
    THRESHOLDS,
    interpret,
    interpret_all,
)

__all__ = [
    "Interpretation",
    "Threshold",
    "THRESHOLDS",
    "NO_REFERENCE",
    "interpret",
    "interpret_all",
]
